loki:
  enabled: true

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true 
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.4.3

prometheus:
  enabled: false
