loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: true 
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.4.0-beta1

prometheus:
  enabled: false
  server:
    fullnameOverride: prometheus-server
