apiVersion: v1
appVersion: 1.5.1
description: Cloud Native storage for containers
home: https://storageos.com
icon: https://storageos.com/wp-content/themes/storageOS/images/logo.svg
keywords:
- storage
- block-storage
- volume
- operator
maintainers:
- email: simon.croome@storageos.com
  name: croomes
- email: sunny.gogoi@storageos.com
  name: darkowlzz
name: storageos-operator
sources:
- https://github.com/storageos
tillerVersion: '>=2.10.0'
version: 0.2.16
