apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
spec:
  template:
    spec:
      containers:
      - name: metrics-server
        command:
          - /metrics-server
          - --kubelet-preferred-address-types=InternalIP
